# Generated by Django 4.1.4 on 2023-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='course/image')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('star', models.FloatField()),
                ('month', models.PositiveSmallIntegerField()),
                ('student', models.PositiveSmallIntegerField()),
                ('books', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.PositiveSmallIntegerField()),
                ('test', models.CharField(max_length=256)),
                ('icon', models.CharField(max_length=70)),
                ('disk', models.PositiveSmallIntegerField(default=50)),
                ('email', models.PositiveSmallIntegerField(default=50)),
                ('bandwidth', models.PositiveSmallIntegerField(default=50)),
                ('subdomain', models.PositiveSmallIntegerField(default=10)),
                ('domain', models.PositiveSmallIntegerField(default=50)),
            ],
        ),
    ]
