# Generated by Django 4.1.4 on 2023-06-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('docs', models.TextField()),
                ('x_loc', models.FloatField()),
                ('y_loc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='course/image')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('star', models.FloatField()),
                ('month', models.PositiveSmallIntegerField()),
                ('student', models.PositiveSmallIntegerField()),
                ('books', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=150)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('duo', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/image/')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.PositiveIntegerField(default=0)),
                ('new', models.BooleanField(default=True)),
                ('note', models.TextField()),
                ('opinion', models.TextField(verbose_name='Teacher opinion')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teacher')),
            ],
        ),
    ]
